/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    categories: Category;
    tags: Tag;
    media: Media;
    pages: Page;
    'hot-topics': HotTopic;
    sources: Source;
    users: User;
    redirects: Redirect;
    'ai-usage': AiUsage;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'hot-topics': HotTopicsSelect<false> | HotTopicsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'ai-usage': AiUsageSelect<false> | AiUsageSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'ai-settings': AiSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * Parte finale dell’indirizzo della pagina. Si genera dal titolo; modificandolo dopo la pubblicazione ricordarsi di creare un redirect.
   */
  slug: string;
  /**
   * Bozza, In revisione, Approvato. Solo un articolo Approvato puo essere pubblicato (RF-B-05).
   */
  editorialStatus: 'bozza' | 'in_revisione' | 'approvato';
  /**
   * Impostata automaticamente alla prima pubblicazione.
   */
  publishedAt?: string | null;
  category: string | Category;
  tags?: (string | Tag)[] | null;
  /**
   * Chi crea l articolo viene inserito automaticamente.
   */
  authors?: (string | User)[] | null;
  /**
   * Riservato a Editor e Amministratori (RF-P-01).
   */
  featured?: boolean | null;
  /**
   * Breve testo sopra il titolo (RF-P-04).
   */
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  /**
   * Usato nelle anteprime, nel feed RSS e come meta description di riserva.
   */
  excerpt?: string | null;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Se lasciati vuoti, il portale usa titolo, sommario e immagine di copertina dell’articolo.
   */
  seo?: {
    /**
     * Consigliati max 60 caratteri: oltre, Google tronca il titolo nei risultati.
     */
    metaTitle?: string | null;
    /**
     * Consigliati max 160 caratteri.
     */
    metaDescription?: string | null;
    /**
     * Formato ideale 1200×630. Usata da Open Graph e Twitter Card (RF-P-06).
     */
    ogImage?: (string | null) | Media;
    /**
     * Solo se il contenuto è pubblicato in originale altrove. Lasciare vuoto nella quasi totalità dei casi.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  /**
   * Se lasciato vuoto, il portale propone automaticamente articoli della stessa categoria che condividono i tag (RF-P-04).
   */
  relatedArticles?: (string | Article)[] | null;
  ai?: {
    origin?: ('manuale' | 'hot_topic' | 'brief' | 'assistenza_editing') | null;
    hotTopic?: (string | null) | HotTopic;
    model?: string | null;
    generatedAt?: string | null;
    /**
     * RF-AI-05.
     */
    brief?: string | null;
    /**
     * Spuntato al passaggio in In revisione. Nessun contenuto AI raggiunge il portale senza questo passaggio (RF-AI-08).
     */
    humanReviewed?: boolean | null;
  };
  searchText?: string | null;
  bodyText?: string | null;
  readingMinutes?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Parte finale dell’indirizzo della pagina. Si genera dal titolo; modificandolo dopo la pubblicazione ricordarsi di creare un redirect.
   */
  slug: string;
  /**
   * Mostrata in testa alla pagina di categoria. Utile anche per la SEO.
   */
  description?: string | null;
  /**
   * Valori più bassi compaiono prima. RF-B-08.
   */
  order?: number | null;
  /**
   * Codice esadecimale (es. #C81E1E) usato dal portale per etichettare la categoria.
   */
  color?: string | null;
  showInMenu?: boolean | null;
  /**
   * Se lasciati vuoti, il portale usa titolo, sommario e immagine di copertina dell’articolo.
   */
  seo?: {
    /**
     * Consigliati max 60 caratteri: oltre, Google tronca il titolo nei risultati.
     */
    metaTitle?: string | null;
    /**
     * Consigliati max 160 caratteri.
     */
    metaDescription?: string | null;
    /**
     * Formato ideale 1200×630. Usata da Open Graph e Twitter Card (RF-P-06).
     */
    ogImage?: (string | null) | Media;
    /**
     * Solo se il contenuto è pubblicato in originale altrove. Lasciare vuoto nella quasi totalità dei casi.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Descrive l’immagine a chi usa uno screen reader ed è richiesto dalle linee guida di accessibilità (RNF-07). Obbligatorio.
   */
  alt: string;
  caption?: string | null;
  /**
   * Es. “Foto: Ansa”. Mostrato sotto l’immagine nell’articolo.
   */
  credit?: string | null;
  /**
   * Impostato automaticamente quando l’immagine arriva dal modulo AI (RF-AI-07).
   */
  aiGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  /**
   * Parte finale dell’indirizzo della pagina. Si genera dal titolo; modificandolo dopo la pubblicazione ricordarsi di creare un redirect.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'redattore' | 'editor' | 'admin';
  /**
   * Disattivare invece di eliminare: cosi’ gli articoli firmati restano attribuiti correttamente.
   */
  active?: boolean | null;
  avatar?: (string | null) | Media;
  /**
   * Mostrata nella pagina autore del portale.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Argomenti emergenti individuati automaticamente dalle fonti configurate. Ordinati per rilevanza.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hot-topics".
 */
export interface HotTopic {
  id: string;
  title: string;
  /**
   * Riassunto generato a partire dalle fonti del cluster.
   */
  summary?: string | null;
  status: 'nuovo' | 'in_lavorazione' | 'convertito' | 'scartato';
  /**
   * Volume x freschezza x affinita con la linea editoriale (RF-AI-03).
   */
  score: number;
  detectedAt: string;
  suggestedCategory?: (string | null) | Category;
  keywords?: string[] | null;
  /**
   * Notizie che hanno concorso a formare questo argomento.
   */
  references?:
    | {
        title: string;
        url: string;
        publisher?: string | null;
        publishedAt?: string | null;
        source?: (string | null) | Source;
        id?: string | null;
      }[]
    | null;
  /**
   * Valorizzato quando un redattore trasforma l argomento in bozza (RF-AI-04).
   */
  generatedArticle?: (string | null) | Article;
  /**
   * Utile per tarare i parametri di rilevanza: se scartiamo sempre lo stesso genere di argomenti, la configurazione va corretta.
   */
  discardReason?: string | null;
  clusterKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fonti interrogate periodicamente per individuare gli hot topic. I costi delle API sono a carico del Committente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: string;
  name: string;
  type: 'rss' | 'newsapi' | 'gdelt' | 'google_trends' | 'custom_http';
  /**
   * Per i feed RSS, l indirizzo del feed. Per le API, l URL base.
   */
  endpoint: string;
  /**
   * Parole chiave o filtri passati alla fonte, se il provider li supporta. Es. "Taranto OR Puglia".
   */
  query?: string | null;
  /**
   * Opzionale: usare solo se questa fonte ha una chiave dedicata. Viene cifrata prima del salvataggio.
   */
  apiKey?: string | null;
  enabled?: boolean | null;
  /**
   * Abbassarla aumenta i costi a consumo sulle fonti a pagamento.
   */
  pollIntervalMinutes?: number | null;
  /**
   * Moltiplicatore applicato agli argomenti che arrivano da questa fonte (RF-AI-03). 1 = neutro.
   */
  weight?: number | null;
  lastFetchedAt?: string | null;
  lastStatus?: ('ok' | 'errore') | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Parte finale dell’indirizzo della pagina. Si genera dal titolo; modificandolo dopo la pubblicazione ricordarsi di creare un redirect.
   */
  slug: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  showInFooter?: boolean | null;
  footerOrder?: number | null;
  /**
   * Se lasciati vuoti, il portale usa titolo, sommario e immagine di copertina dell’articolo.
   */
  seo?: {
    /**
     * Consigliati max 60 caratteri: oltre, Google tronca il titolo nei risultati.
     */
    metaTitle?: string | null;
    /**
     * Consigliati max 160 caratteri.
     */
    metaDescription?: string | null;
    /**
     * Formato ideale 1200×630. Usata da Open Graph e Twitter Card (RF-P-06).
     */
    ogImage?: (string | null) | Media;
    /**
     * Solo se il contenuto è pubblicato in originale altrove. Lasciare vuoto nella quasi totalità dei casi.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reindirizzamenti applicati dal portale prima di servire una pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Es. /vecchia-sezione/articolo-di-ieri
   */
  from: string;
  /**
   * Percorso interno (es. /nuovo-articolo) oppure URL assoluto.
   */
  to: string;
  type: '301' | '302';
  active?: boolean | null;
  /**
   * Perche esiste questo redirect. Aiuta chi lo ritrovera fra sei mesi.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chiamate effettuate ai provider esterni. I costi sono fatturati direttamente al Committente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage".
 */
export interface AiUsage {
  id: string;
  provider: string;
  model: string;
  operation:
    | 'hot_topic_ranking'
    | 'draft_from_topic'
    | 'draft_from_brief'
    | 'rewrite'
    | 'summarize'
    | 'title_suggestions'
    | 'seo_suggestions'
    | 'image_generation'
    | 'comment_moderation';
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
  /**
   * Stima calcolata sul listino configurato in Impostazioni AI. Fa fede la fattura del provider.
   */
  estimatedCostEur?: number | null;
  durationMs?: number | null;
  success?: boolean | null;
  errorMessage?: string | null;
  /**
   * Vuoto se la chiamata proviene da un job automatico.
   */
  user?: (string | null) | User;
  article?: (string | null) | Article;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chi ha fatto cosa, e quando. Sola lettura.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: string;
  action: 'creazione' | 'modifica' | 'eliminazione';
  collectionSlug: string;
  documentId: string;
  documentLabel?: string | null;
  user?: (string | null) | User;
  statusFrom?: string | null;
  statusTo?: string | null;
  /**
   * Solo i nomi dei campi: il contenuto e nelle revisioni (RF-B-13).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'hot-topics';
        value: string | HotTopic;
      } | null)
    | ({
        relationTo: 'sources';
        value: string | Source;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'ai-usage';
        value: string | AiUsage;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  publishedAt?: T;
  category?: T;
  tags?: T;
  authors?: T;
  featured?: T;
  kicker?: T;
  title?: T;
  subtitle?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  relatedArticles?: T;
  ai?:
    | T
    | {
        origin?: T;
        hotTopic?: T;
        model?: T;
        generatedAt?: T;
        brief?: T;
        humanReviewed?: T;
      };
  searchText?: T;
  bodyText?: T;
  readingMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  color?: T;
  showInMenu?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  aiGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  content?: T;
  showInFooter?: T;
  footerOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hot-topics_select".
 */
export interface HotTopicsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  status?: T;
  score?: T;
  detectedAt?: T;
  suggestedCategory?: T;
  keywords?: T;
  references?:
    | T
    | {
        title?: T;
        url?: T;
        publisher?: T;
        publishedAt?: T;
        source?: T;
        id?: T;
      };
  generatedArticle?: T;
  discardReason?: T;
  clusterKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  endpoint?: T;
  query?: T;
  apiKey?: T;
  enabled?: T;
  pollIntervalMinutes?: T;
  weight?: T;
  lastFetchedAt?: T;
  lastStatus?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  avatar?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  active?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage_select".
 */
export interface AiUsageSelect<T extends boolean = true> {
  provider?: T;
  model?: T;
  operation?: T;
  inputTokens?: T;
  outputTokens?: T;
  totalTokens?: T;
  estimatedCostEur?: T;
  durationMs?: T;
  success?: T;
  errorMessage?: T;
  user?: T;
  article?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  documentLabel?: T;
  user?: T;
  statusFrom?: T;
  statusTo?: T;
  changedFields?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  /**
   * Compare accanto al nome nei risultati di ricerca e nel feed.
   */
  tagline?: string | null;
  logo?: (string | null) | Media;
  /**
   * Usata quando un contenuto non ha ne immagine social ne copertina (RF-P-06). Formato 1200x630.
   */
  defaultOgImage?: (string | null) | Media;
  /**
   * Ragione sociale usata nei dati strutturati schema.org come Publisher (RF-P-07).
   */
  publisherName?: string | null;
  /**
   * Es. "Quotidiano online di politica e attualità. Registrazione Tribunale di Roma n. 214/2024."
   */
  legalNotice?: string | null;
  /**
   * Es. "P. IVA 04871230581 — Via dei Serpenti 42, 00184 Roma".
   */
  companyDetails?: string | null;
  editorInChief?: string | null;
  /**
   * Se valorizzata, ha la precedenza sugli articoli marcati In evidenza. Vuota = ordinamento automatico per data (RF-P-01).
   */
  featuredArticles?: (string | Article)[] | null;
  /**
   * Blocchi di categoria mostrati sotto le ultime notizie.
   */
  homeSections?:
    | {
        category: string | Category;
        title?: string | null;
        limit?: number | null;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'linkedin' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Senza @. Usato nella Twitter Card (RF-P-06).
   */
  twitterHandle?: string | null;
  contactEmail?: string | null;
  cookieBanner?: {
    enabled?: boolean | null;
    message?: string | null;
    privacyPage?: (string | null) | Page;
    cookiePage?: (string | null) | Page;
  };
  analytics?: {
    /**
     * Plausible e Umami non usano cookie e non richiedono consenso preventivo: sono la scelta piu semplice sul piano GDPR (RNF-04).
     */
    provider?: ('nessuno' | 'plausible' | 'umami' | 'ga4') | null;
    siteId?: string | null;
    scriptUrl?: string | null;
  };
  maintenanceMode?: boolean | null;
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Provider, modelli e criteri di rilevanza del modulo AI. I costi delle chiamate sono a carico del Committente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: string;
  /**
   * Se disattivato, gli strumenti AI spariscono dal backoffice con un messaggio informativo e il resto della piattaforma continua a funzionare normalmente (RNF-10).
   */
  enabled?: boolean | null;
  disabledMessage?: string | null;
  /**
   * Superata questa soglia il backoffice mostra un avviso. Non blocca le chiamate: serve a rendere visibile il consumo (RF-AI-10).
   */
  monthlyBudgetEur?: number | null;
  /**
   * Chiave intestata al Committente. Cifrata prima del salvataggio, mai restituita in chiaro (RF-AI-09).
   */
  anthropicApiKey?: string | null;
  /**
   * Usato per bozze da hot topic e da brief. Il costo per articolo dipende soprattutto da questa scelta.
   */
  textModel: 'claude-opus-5' | 'claude-sonnet-5' | 'claude-haiku-4-5';
  /**
   * Clustering degli hot topic, titoli alternativi, moderazione automatica. Sono operazioni ad alto volume: qui conviene il modello economico.
   */
  utilityModel: 'claude-haiku-4-5' | 'claude-sonnet-5' | 'claude-opus-5';
  /**
   * Alza la qualità e il costo delle generazioni. Conviene tararla dopo qualche settimana di uso reale.
   */
  effort?: ('low' | 'medium' | 'high' | 'xhigh') | null;
  /**
   * Prezzi in USD per milione di token, usati per stimare la spesa nel registro consumi.
   */
  pricing?:
    | {
        model: string;
        inputPerMillion: number;
        outputPerMillion: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Usato solo per la stima interna dei costi.
   */
  usdToEur?: number | null;
  /**
   * Testo libero: chi siamo, di cosa ci occupiamo, a chi parliamo, che taglio diamo alle notizie. È il contesto che orienta sia il ranking degli hot topic sia il tono delle bozze generate.
   */
  editorialProfile?: string | null;
  /**
   * Es. cronaca locale, economia del mare, politica regionale.
   */
  themes?: string[] | null;
  boostKeywords?: string[] | null;
  /**
   * Argomenti che non vogliamo mai vedere proposti fra gli hot topic.
   */
  excludeKeywords?: string[] | null;
  toneOfVoice?: string | null;
  /**
   * Gli argomenti sotto questo punteggio non vengono proposti alla redazione. Alzarla riduce il rumore, abbassarla amplia il campo.
   */
  minScore?: number | null;
  maxTopicsPerRun?: number | null;
  imagesEnabled?: boolean | null;
  imageProvider?: ('nessuno' | 'openai' | 'stability' | 'replicate') | null;
  /**
   * La chiave viene cifrata prima del salvataggio. Lasciare la maschera invariata per non modificarla.
   */
  imageApiKey?: string | null;
  /**
   * Inserita nei crediti dell’immagine. Serve a non spacciare per fotografia ciò che non lo è.
   */
  imageDisclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  defaultOgImage?: T;
  publisherName?: T;
  legalNotice?: T;
  companyDetails?: T;
  editorInChief?: T;
  featuredArticles?: T;
  homeSections?:
    | T
    | {
        category?: T;
        title?: T;
        limit?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  twitterHandle?: T;
  contactEmail?: T;
  cookieBanner?:
    | T
    | {
        enabled?: T;
        message?: T;
        privacyPage?: T;
        cookiePage?: T;
      };
  analytics?:
    | T
    | {
        provider?: T;
        siteId?: T;
        scriptUrl?: T;
      };
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  enabled?: T;
  disabledMessage?: T;
  monthlyBudgetEur?: T;
  anthropicApiKey?: T;
  textModel?: T;
  utilityModel?: T;
  effort?: T;
  pricing?:
    | T
    | {
        model?: T;
        inputPerMillion?: T;
        outputPerMillion?: T;
        id?: T;
      };
  usdToEur?: T;
  editorialProfile?: T;
  themes?: T;
  boostKeywords?: T;
  excludeKeywords?: T;
  toneOfVoice?: T;
  minScore?: T;
  maxTopicsPerRun?: T;
  imagesEnabled?: T;
  imageProvider?: T;
  imageApiKey?: T;
  imageDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'articles';
      value: string | Article;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}